# Credit Risk Resampling Techniques

In [264]:
import warnings
warnings.filterwarnings('ignore')

In [265]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.preprocessing import LabelEncoder

# Read the CSV into DataFrame

In [266]:
# Load the data
file_path = Path('Resources/lending_data.csv')
df = pd.read_csv(file_path)
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

In [267]:
label_encoder = LabelEncoder()

In [268]:
label_encoder.fit(df["loan_status"])

LabelEncoder()

In [269]:
list(label_encoder.classes_)

['high_risk', 'low_risk']

In [270]:
df["loan_status_int"] = label_encoder.transform(df["loan_status"])
df.tail()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
77531    19100.0         11.261       own            86600        0.653580   
77532    17700.0         10.662  mortgage            80900        0.629172   
77533    17600.0         10.595      rent            80300        0.626401   
77534    16300.0         10.068  mortgage            75300        0.601594   
77535    15600.0          9.742  mortgage            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt loan_status  \
77531               12                 2       56600   high_risk   
77532               11                 2       50900   high_risk   
77533               11                 2       50300   high_risk   
77534               10                 2       45300   high_risk   
77535                9                 2       42300   high_risk   

       loan_status_int  
77531                0  
77532                0  
77533                0  
77534                0  
77535                0

In [271]:
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  loan_status_int  
0                5                 1       22800    low_risk                1  
1                3                 0       13600    low_risk                1  
2                3                 0       16100    low_risk                1  
3                5                 1       22700    low_risk                1  
4                5                 1       23000    low_risk                1

In [272]:
df.drop(["loan_status"], axis=1, inplace=True)
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt  loan_status_int  
0                5                 1       22800                1  
1                3                 0       13600                1  
2                3                 0       16100                1  
3                5                 1       22700                1  
4                5                 1       23000                1

In [273]:
#df.rename(columns={"loan_status_int":"loan_status"})
#df.head()

# Split the Data into Training and Testing

In [275]:
# Create our target
y = df['loan_status_int'] # YOUR CODE HERE

# Create our features
X = df.drop(columns=['loan_status_int','homeowner']) # YOUR CODE HERE

In [276]:
X

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                    3                 0       16100  
3                    5                 1       22700  
4                    5                 1       23000  
...                ...               ...         ...  
77531               12                 2       56600  
77532               11                 2       50900  
77533               11                 2       50300  
77534               10                 2       45300  
77535                9                 2       42300  

[77536 rows x 7 columns]

In [277]:
y = y.to_frame()
y

loan_status_int
0                    1
1                    1
2                    1
3                    1
4                    1
...                ...
77531                0
77532                0
77533                0
77534                0
77535                0

[77536 rows x 1 columns]

In [278]:
X.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  77536.000000   77536.000000     77536.000000    77536.000000   
mean    9805.562577       7.292333     49221.949804        0.377318   
std     2093.223153       0.889495      8371.635077        0.081519   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.825000     44800.000000        0.330357   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.528000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt  
count     77536.000000      77536.000000  77536.000000  
mean          3.826610          0.392308  19221.949804  
std           1.904426          0.582086   8371.635077  
min           0.000000          0.000000      0.000000  
25%           3.000000          0.000000  14800.000000  
50%           4.000000          0.000000  18100.000000  
75%           4.000000          1.000000  21400.000000  
max          16.000000          3.000000  75200.000000

In [280]:
# Check the balance of our target values
y['loan_status_int'].value_counts()

1    75036
0     2500
Name: loan_status_int, dtype: int64

In [281]:
# Create X_train, X_test, y_train, y_test
# YOUR CODE HERE
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, 
                                                   y, 
                                                   random_state=1, 
                                                   stratify=y)
X_train.shape

(58152, 7)

In [282]:
X_train.head()

loan_size  interest_rate  borrower_income  debt_to_income  \
25729    10100.0          7.402            50300        0.403579   
20176     9200.0          7.049            46900        0.360341   
55080     8800.0          6.870            45200        0.336283   
10410     8900.0          6.919            45700        0.343545   
63110     8500.0          6.731            43900        0.316629   

       num_of_accounts  derogatory_marks  total_debt  
25729                4                 1       20300  
20176                3                 0       16900  
55080                3                 0       15200  
10410                3                 0       15700  
63110                3                 0       13900

In [283]:
X_test.head()

loan_size  interest_rate  borrower_income  debt_to_income  \
37214    11500.0          8.017            56000        0.464286   
2791      9700.0          7.227            48600        0.382716   
75901    16900.0         10.312            77600        0.613402   
70752    10600.0          7.632            52400        0.427481   
54071    11300.0          7.936            55300        0.457505   

       num_of_accounts  derogatory_marks  total_debt  
37214                5                 1       26000  
2791                 4                 0       18600  
75901               10                 2       47600  
70752                5                 1       22400  
54071                5                 1       25300

In [284]:
y_train.head()

loan_status_int
25729                1
20176                1
55080                1
10410                1
63110                1

In [285]:
y_test.head()

loan_status_int
37214                1
2791                 1
75901                0
70752                1
54071                1

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [286]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
# YOUR CODE HERE
data_scaler = StandardScaler()

In [287]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
# YOUR CODE HERE

data_scaler.fit(X_train)

StandardScaler()

In [288]:
#Mean of X_train
data_scaler.mean_

array([9.80612533e+03, 7.29255941e+00, 4.92239476e+04, 3.77350994e-01,
       3.82654079e+00, 3.92351080e-01, 1.92239476e+04])

In [289]:
#Variance of X_train
data_scaler.scale_

array([2.09228589e+03, 8.89098773e-01, 8.36777768e+03, 8.14841689e-02,
       1.90296901e+00, 5.81506944e-01, 8.36777768e+03])

In [290]:
# Scale the training and testing data
# YOUR CODE HERE
X_train_scaled = data_scaler.transform(X_train)
X_test_scaled = data_scaler.transform(X_test)

In [291]:
X_train_scaled

array([[ 0.14045627,  0.1230916 ,  0.12859477, ...,  0.09115188,
         1.04495557,  0.12859477],
       [-0.28969527, -0.27393966, -0.27772578, ..., -0.43434275,
        -0.67471435, -0.27772578],
       [-0.48087373, -0.47526712, -0.48088605, ..., -0.43434275,
        -0.67471435, -0.48088605],
       ...,
       [-1.48456066, -1.46728289, -1.47278621, ..., -1.48533201,
        -0.67471435, -1.47278621],
       [-0.28969527, -0.26831599, -0.26577518, ..., -0.43434275,
        -0.67471435, -0.26577518],
       [-1.05440912, -1.05787955, -1.05451506, ..., -0.95983738,
        -0.67471435, -1.05451506]])

In [292]:
#Mean of scaled X_train
print(X_train_scaled.mean(axis=0))

[ 7.95438370e-17  1.60773857e-15  2.10284091e-16 -3.06445381e-16
 -4.28876909e-17 -2.46818050e-17  2.10284091e-16]


In [293]:
#Variance of scaled X_train
print(X_train_scaled.std(axis=0))

[1. 1. 1. 1. 1. 1. 1.]


In [294]:
X_test_scaled

array([[ 0.80958089,  0.81480327,  0.80977921, ...,  0.61664652,
         1.04495557,  0.80977921],
       [-0.05072219, -0.07373693, -0.07456551, ...,  0.09115188,
        -0.67471435, -0.07456551],
       [ 3.39049014,  3.39606878,  3.39110974, ...,  3.24411968,
         2.76462549,  3.39110974],
       ...,
       [ 0.57060781,  0.58423271,  0.58271773, ...,  0.61664652,
         1.04495557,  0.58271773],
       [ 0.61840243,  0.63484576,  0.63052015, ...,  0.61664652,
         1.04495557,  0.63052015],
       [ 0.18825089,  0.18045305,  0.17639718, ...,  0.09115188,
         1.04495557,  0.17639718]])

# Simple Logistic Regression

In [295]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=1)

In [296]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.9892813049736127

In [297]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  615,    10],
       [  102, 18657]], dtype=int64)

In [298]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.86      0.98      0.99      0.92      0.99      0.98       625
          1       1.00      0.99      0.98      1.00      0.99      0.98     18759

avg / total       0.99      0.99      0.98      0.99      0.99      0.98     19384



# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [299]:
# Resample the training data with the RandomOversampler
# YOUR CODE HERE
# implement random oversampling
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)


# View the count of target classes with Counter
# YOUR CODE HERE
Counter(y_resampled)

Counter({'loan_status_int': 1})

In [300]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [301]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9892813049736127

In [302]:
# Display the confusion matrix
# YOUR CODE HERE
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test_scaled)
confusion_matrix(y_test, y_pred)

array([[  622,     3],
       [  111, 18648]], dtype=int64)

In [303]:
# Print the imbalanced classification report
# YOUR CODE HERE
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.85      1.00      0.99      0.92      0.99      0.99       625
          1       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       0.99      0.99      1.00      0.99      0.99      0.99     19384



### SMOTE Oversampling

In [304]:
# Resample the training data with SMOTE
# YOUR CODE HERE
from imblearn.over_sampling import SMOTE

X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy=1.0).fit_resample(
    X_train_scaled, y_train
)

# View the count of target classes with Counter
# YOUR CODE HERE
from collections import Counter

Counter(y_resampled)

Counter({'loan_status_int': 1})

In [305]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [306]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.9946414201183431

In [307]:
# Display the confusion matrix
# YOUR CODE HERE
confusion_matrix(y_test, y_pred)

array([[  622,     3],
       [  111, 18648]], dtype=int64)

In [308]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.85      1.00      0.99      0.92      0.99      0.99       625
          1       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       0.99      0.99      1.00      0.99      0.99      0.99     19384



# Undersampling

In this section, you will test an undersampling algorithm to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [309]:
# Resample the data using the ClusterCentroids resampler
# YOUR CODE HERE
from imblearn.under_sampling import ClusterCentroids

cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train_scaled, y_train)

# View the count of target classes with Counter
# YOUR CODE HERE
from collections import Counter

Counter(y_resampled)

Counter({'loan_status_int': 1})

In [310]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [311]:
# Calculate the balanced accuracy score
# YOUR CODE HERE
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9946414201183431

In [312]:
# Display the confusion matrix
# YOUR CODE HERE
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test_scaled)
confusion_matrix(y_test, y_pred)

array([[  620,     5],
       [  104, 18655]], dtype=int64)

In [313]:
# Print the imbalanced classification report
# YOUR CODE HERE
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.86      0.99      0.99      0.92      0.99      0.99       625
          1       1.00      0.99      0.99      1.00      0.99      0.99     18759

avg / total       1.00      0.99      0.99      0.99      0.99      0.99     19384



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [314]:
# Resample the training data with SMOTEENN
# YOUR CODE HERE
from imblearn.combine import SMOTEENN

sm = SMOTEENN(random_state=1)
X_resampled, y_resampled = sm.fit_resample(X_train_scaled, y_train)

# View the count of target classes with Counter
# YOUR CODE HERE
Counter(y_resampled)

Counter({'loan_status_int': 1})

In [315]:
# Train the Logistic Regression model using the resampled data
# YOUR CODE HERE
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [316]:
# Calculate the balanced accuracy score
# YOUR CODE HERE
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9932279972279972

In [317]:
# Display the confusion matrix
# YOUR CODE HERE
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test_scaled)
confusion_matrix(y_test, y_pred)

array([[  622,     3],
       [  111, 18648]], dtype=int64)

In [318]:
# Print the imbalanced classification report
# YOUR CODE HERE
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.85      1.00      0.99      0.92      0.99      0.99       625
          1       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       0.99      0.99      1.00      0.99      0.99      0.99     19384



# Final Questions

1. Which model had the best balanced accuracy score?

   YOUR ANSWER HERE.

2. Which model had the best recall score?

    YOUR ANSWER HERE.

3. Which model had the best geometric mean score?

    YOUR ANSWER HERE.
